apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-hello-world
  name: app-cicd-hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-hello-world
  template:
    metadata:
      labels:
        app: cicd-hello-world
    spec:
      containers:
        - name: cicd-hello-world-server
          image: gdubdubs/cicd-hello-world:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhub-gdubdubs  
  strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0


---

apiVersion: v1
kind: Service
metadata:
  name: cicd-hello-world-service
  labels:
    name: cicd-hello-world-service
spec:
  type: LoadBalancer
  loadBalancerIP: IP_LOADBALANCER
  ports:
  - port: 8099
    targetPort: 3000
  selector:
    app: cicd-hello-world